/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Escrow } from "./Escrow";
export type { FranekTataToken } from "./FranekTataToken";
export type { FranekTataTokenUpgradeable } from "./FranekTataTokenUpgradeable";
export type { FranekTataTokenUpgradeableV2 } from "./FranekTataTokenUpgradeableV2";
export type { FranekekosKokosNFT } from "./FranekekosKokosNFT";
export type { FranekosKokosNFT } from "./FranekosKokosNFT";
export type { GovernanceToken } from "./GovernanceToken";
export type { MyGovernor } from "./MyGovernor";
export type { StorageSlot } from "./StorageSlot";
