/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { PayableOverrides } from "../../common";
import type { Escrow, EscrowInterface } from "../../contracts/Escrow";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_arbiter",
        type: "address",
      },
      {
        internalType: "address",
        name: "_beneficiary",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "Approved",
    type: "event",
  },
  {
    inputs: [],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "arbiter",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "beneficiary",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "depositor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isApproved",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405260405161031d38038061031d8339810160408190526020916079565b5f80546001600160a01b039384166001600160a01b031991821617909155600180549290931691811691909117909155600280549091163317905560a5565b80516001600160a01b03811681146074575f5ffd5b919050565b5f5f604083850312156089575f5ffd5b609083605f565b9150609c60208401605f565b90509250929050565b61026b806100b25f395ff3fe608060405234801561000f575f5ffd5b5060043610610055575f3560e01c806312424e3f1461005957806328f371aa1461006357806338af3eed1461008c578063c7c4ff46146100b7578063fe25e00a146100ca575b5f5ffd5b6100616100dc565b005b60025461007790600160a01b900460ff1681565b60405190151581526020015b60405180910390f35b60015461009f906001600160a01b031681565b6040516001600160a01b039091168152602001610083565b60025461009f906001600160a01b031681565b5f5461009f906001600160a01b031681565b5f546001600160a01b031633146100f1575f5ffd5b600254600160a01b900460ff16156101505760405162461bcd60e51b815260206004820152601760248201527f457363726f7720616c726561647920617070726f76656400000000000000000060448201526064015b60405180910390fd5b60015460405147915f916001600160a01b039091169083908381818185875af1925050503d805f811461019e576040519150601f19603f3d011682016040523d82523d5f602084013e6101a3565b606091505b50509050806101eb5760405162461bcd60e51b81526020600482015260146024820152732330b4b632b2103a379039b2b7321022ba3432b960611b6044820152606401610147565b6040518281527f3ad93af63cb7967b23e4fb500b7d7d28b07516325dcf341f88bebf959d82c1cb9060200160405180910390a150506002805460ff60a01b1916600160a01b17905556fea26469706673582212200be00fad03317e30b5ff1957911b343afa3a4f4bec36f3539dd3503ab4b1f4a564736f6c634300081c0033";

type EscrowConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EscrowConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Escrow__factory extends ContractFactory {
  constructor(...args: EscrowConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _arbiter: AddressLike,
    _beneficiary: AddressLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_arbiter, _beneficiary, overrides || {});
  }
  override deploy(
    _arbiter: AddressLike,
    _beneficiary: AddressLike,
    overrides?: PayableOverrides & { from?: string }
  ) {
    return super.deploy(_arbiter, _beneficiary, overrides || {}) as Promise<
      Escrow & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Escrow__factory {
    return super.connect(runner) as Escrow__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EscrowInterface {
    return new Interface(_abi) as EscrowInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Escrow {
    return new Contract(address, _abi, runner) as unknown as Escrow;
  }
}
