/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  StorageSlot,
  StorageSlotInterface,
} from "../../contracts/StorageSlot";

const _abi = [
  {
    inputs: [],
    name: "a",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "b",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balances",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "c",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "setBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052602a5f55600180546001600160a81b031916740112345678901234567890123456789012345678901790553480156039575f5ffd5b5061017d806100475f395ff3fe608060405234801561000f575f5ffd5b5060043610610055575f3560e01c80630dbe671f1461005957806327e235e3146100745780634df7e3d014610093578063c3da42b8146100be578063fb1669ca146100e2575b5f5ffd5b6100615f5481565b6040519081526020015b60405180910390f35b610061610082366004610103565b60026020525f908152604090205481565b6001546100a6906001600160a01b031681565b6040516001600160a01b03909116815260200161006b565b6001546100d290600160a01b900460ff1681565b604051901515815260200161006b565b6101016100f0366004610130565b335f90815260026020526040902055565b005b5f60208284031215610113575f5ffd5b81356001600160a01b0381168114610129575f5ffd5b9392505050565b5f60208284031215610140575f5ffd5b503591905056fea2646970667358221220c39b0f67c262db0432552039ae7d065aff38fef7f532e5dd8e30b79a3db8668864736f6c634300081c0033";

type StorageSlotConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StorageSlotConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StorageSlot__factory extends ContractFactory {
  constructor(...args: StorageSlotConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      StorageSlot & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): StorageSlot__factory {
    return super.connect(runner) as StorageSlot__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StorageSlotInterface {
    return new Interface(_abi) as StorageSlotInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): StorageSlot {
    return new Contract(address, _abi, runner) as unknown as StorageSlot;
  }
}
